### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by waweic** [gianluca-nitti/android-expr-eval#3]
Please put Every String in your App to strings.xml so anybody is able to translate.

**Comment by gianluca-nitti** [comment]
Thank you for the suggestion. Added to the to-do list.

**Comment by gianluca-nitti** [comment]
@waweic Ok, the application is now fully localizable. I also added the Italian (my native language) strings.xml.

If you want to submit a translation, you could fork the repository and then open a PR with your changes, or post here / send me the strings.xml, as you want.

Again thank you for reporting the issue, initially I used string literals in code and layouts because I didn't think this, as a small app, was worth translating. Sorry if this took long but I had to make some changes in the [library](https://github.com/gianluca-nitti/java-expr-eval) too to make it compatible with the Android localization system.
