### ISSUE TITLE
1.1 won't open on Kindle Fire HDX

### ISSUE THREAD

**Issue by aacero** [gianluca-nitti/android-expr-eval#4]
1.0 works well.
Both downloaded from f-droid.org

**Comment by gianluca-nitti** [comment]
Thank you for reporting.  Yesterday I found out that 1.1 crashes on startup on a Jelly Bean tablet too, while on Android 6.0+ phones and emulators everything works fine. I think I already found a solution, it should be due to outdated build tools specified in the gradle configuration. I'll probably fix this soon.

In the meanwhile can you please specify what Android version are you running?

**Comment by aacero** [comment]
It's running FireOS 13.3.2.4_... with a build date of June 20, 2014 -- it probably corresponds to Jelly Bean, but I'm not sure.

1.2 hasn't shown up in the f-droid.org repo yet.

**Comment by gianluca-nitti** [comment]
1.2 works on my Jelly Bean tablet and is in F-droid (I had to refresh the repository to update, but it probably depends on your auto-update settings). Let me know if it's fixed for you too.

**Comment by aacero** [comment]
It is working for me as well, thanks!
